# __Numpy__

In [1]:
# import library = numpy
import numpy as np

### **Creating Numpy Array**

### 1. from Python List

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
type(np.array(my_list))

numpy.ndarray

In [4]:
my_matrix = [ [1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)
#array 2 dimensi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
my_3dlist=[[ [1,2],[3,4] ],[ [5,6],[7,8] ]]
np.array(my_3dlist)
#array 3 dimensi

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 2. Built-in methods arange

In [6]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
y= np.arange(0,10,2) #(start, stop, step)
y

array([0, 2, 4, 6, 8])

In [9]:
type(x)

numpy.ndarray

In [10]:
type(y)

numpy.ndarray

## **Mini Activity**

- **Group 1** : 
- np.linspace, 
- np.zeros, 
- arr.shape,
- arr.reshape

- **Group 2**: 
- np.ones,  
- np.random.rand, 
- np.random.randn, 
- np.random.randint


- **Group 3**: 
- arr.max, 
- arr.argmax, 
- arr.min, 
- arr.argmin, 
- arr.dtype

Cara pemakaian  
Fungsi method  
Aplikasinya apa  

### 3. Built-in methods = zeros & ones

In [11]:
np.zeros(7) #untuk membuat array berisi angka 0, sesuai shape yang kita input

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5) #membuat array berisi angka 1, sesuai shape yang kita input

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# arr = np.arange(0,10)
# arr

### 4. Built-in methods = linspace (jarak antar data bisa diketahui dan sama)

In [16]:
np.linspace(1,1000,25) #membuat array yang memiliki jarak antar elemen yang sama. parameter yang dimasukan: start, stop (included), num(jumlah angka) 

array([   1.   ,   42.625,   84.25 ,  125.875,  167.5  ,  209.125,
        250.75 ,  292.375,  334.   ,  375.625,  417.25 ,  458.875,
        500.5  ,  542.125,  583.75 ,  625.375,  667.   ,  708.625,
        750.25 ,  791.875,  833.5  ,  875.125,  916.75 ,  958.375,
       1000.   ])

In [17]:
np.linspace(10, 100, 10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 5. Built-in methods = eye

In [19]:
np.eye(5, 5) #membuat array beisi angka 0 dan angka 1 di posisi diagonal array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 6. Built-in methods = random.rand (membuat array dengan value random, dari 0 - 1)

In [20]:
np.random.rand(10) #parameter berupa jumlah/shape angka yang kita inginkan

array([0.32849399, 0.12888453, 0.08418143, 0.75176809, 0.04997129,
       0.23814988, 0.54533425, 0.95259661, 0.84630752, 0.16272596])

In [21]:
np.random.rand(5,5)

array([[0.78142028, 0.84170938, 0.4656752 , 0.82728334, 0.73812106],
       [0.40682889, 0.64744674, 0.25900921, 0.72583796, 0.1560105 ],
       [0.3761603 , 0.33420256, 0.9805755 , 0.48946725, 0.6505171 ],
       [0.16354891, 0.1168294 , 0.81126775, 0.3016189 , 0.3475489 ],
       [0.68294141, 0.01046868, 0.42038693, 0.98666717, 0.9454351 ]])

### 7. Built-in methods = random.randn (membuat array dengan value random dan datanya terdistribusi normal)

In [22]:
np.random.randn(10) #parameter berupa jumlah/shape array yang kita inginkan

array([-0.73905865,  1.08645984, -0.29178517, -0.20946951, -0.32000435,
        1.63681827, -0.07075984, -0.91961375, -0.49524675,  0.82474314])

In [23]:
np.random.randn(5,5)

array([[ 0.44735768,  0.51266519,  1.01609931,  0.90536317,  0.82104852],
       [-0.43918848, -0.92979408, -0.13167621,  0.37155532, -0.95780712],
       [-0.43249481, -0.47115992, -0.16178913, -0.52253184,  0.50496732],
       [-1.30655319,  0.72578561, -2.49132897,  0.22955367,  1.15729155],
       [ 0.83434038,  0.19322997,  0.06720764, -1.33750984,  0.85741128]])

### 8. Built-in methods = random.randint (membuat array dengan value random dan datanya berupa integer)

In [28]:
np.random.randint(1,15) #mencari data random dari 1 sampai 15

1

In [31]:
np.random.randint(21,51,10) #mencari data random dari 21 sampai 51 sebanyak 10 data

array([34, 44, 24, 35, 34, 32, 24, 28, 50, 47])

## **Array Attributes**

In [49]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([ 5,  2, 16, 38, 34, 44, 14, 29,  0, 10])

In [36]:
# untuk mengubah dimensi
x = arr.reshape(2,5,2) #shape baru harus sesuai dengan jumlah elemen di dalam array
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [37]:
# mengetahui dimensi/bentuk
x.shape #outout (2,5,2) --> array 3 dimensi berukuran 2x5x2

(2, 5, 2)

In [38]:
#mencari nilai terbesar dalam array
ranarr.max() 

44

In [39]:
# mencari index nilai terbesar dalam array
ranarr.argmax()

5

In [40]:
#mencari nilai terkecil dalam array
ranarr.min()

0

In [41]:
# mencari index nilai terkecil dalam array
ranarr.argmin()

8

In [50]:
#mengetahui tipe data
arr.dtype

dtype('int32')

In [52]:
arr=arr.astype('float64')
arr.dtype

dtype('float64')

In [53]:
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [54]:
arr=np.int64(arr)
arr.dtype


dtype('int64')

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

# **Indexing** : menampilkan sesuai index tertentu

In [56]:
a = np.arange(11, 21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
# menampilkan index ke-8
a[8]

19

In [59]:
# menampilkan index start: 0, stop: 8, step:2
a[0:8:2]

array([11, 13, 15, 17])

In [60]:
a=a.reshape(2,5)
a

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [61]:
#indexing 2 dimensi
a[0][1]

12

# **Broadcasting**

In [64]:
a=a. reshape(10)

In [65]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [66]:
a[0:4] = 0
a

array([ 0,  0,  0,  0, 15, 16, 17, 18, 19, 20])

# **Slicing**

In [77]:
slice_of_a = a[5:9]
slice_of_a[0:]=1

In [78]:
a #nilai di a berubah karena slice_of_a hanya berupa view dari array a

array([ 0,  0,  0,  0, 15,  1,  1,  1,  1, 20])

# **Copy**

In [72]:
c = a[5:10].copy()
c

array([16, 17, 18, 19, 20])

# **Indexing 2D Array**

In [79]:
arr_2d = np.array(([5,10,15],[20,25,10],[15,35,25]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 10],
       [15, 35, 25]])

In [80]:
yo= arr_2d[0,1],arr_2d[1,1],arr_2d[2,1]
np.array(yo)

array([10, 25, 35])

In [81]:
arr_2d[1]

array([20, 25, 10])

In [82]:
arr_2d[1][2]

10

In [83]:
arr_2d[1,2]

10

# **2D Array Slicing**

In [86]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 10],
       [15, 35, 25]])

In [84]:
arr_2d[:3, :2]

array([[ 5, 10],
       [20, 25],
       [15, 35]])

In [87]:
arr_2d[2]

array([15, 35, 25])

In [88]:
arr_2d[2, :]

array([15, 35, 25])

# **Lenght of Array**

In [99]:
arr2d = np.zeros((10, 5,2))
arr2d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [100]:
len(arr2d)

10

In [103]:
arr2d.shape

(10, 5, 2)

In [101]:
arr_length = arr2d.shape[0]
arr_length

10

# **Selection**

In [104]:
gaji = np.arange(5, 25)

In [106]:
gaji

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [105]:
# selection gaji di atas 10 juta
gaji > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [107]:
bool_gaji = gaji > 10
gaji[bool_gaji]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [108]:
gaji[gaji > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [109]:
gaji[gaji < 15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# **Aritmetic**

In [112]:
x = np.arange(5, 15)
y = np.arange(15, 25)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [111]:
y

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
x + x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [114]:
y - x

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [115]:
y / x

array([3.        , 2.66666667, 2.42857143, 2.25      , 2.11111111,
       2.        , 1.90909091, 1.83333333, 1.76923077, 1.71428571])

In [116]:
x * y

array([ 75,  96, 119, 144, 171, 200, 231, 264, 299, 336])

In [117]:
pangkat_dua = x ** 2
pangkat_dua

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196], dtype=int32)

In [119]:
np.sqrt(pangkat_dua)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.])

In [120]:
np.exp(x)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06])

In [122]:
np.sin(x)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [123]:
np.log(x)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [125]:
z=x.reshape(2,5)
z

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
z*2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [127]:
a=np.arange(1,4)
a

array([1, 2, 3])

In [128]:
z*a

ValueError: operands could not be broadcast together with shapes (2,5) (3,) 

In [133]:
b=np.arange(2,7)
b

array([2, 3, 4, 5, 6])

In [134]:
z*b

array([[10, 18, 28, 40, 54],
       [20, 33, 48, 65, 84]])

In [148]:
c=np.array([[1],[2]])
c

array([[1],
       [2]])

In [149]:
c.shape

(2, 1)

In [150]:
z*c

array([[ 5,  6,  7,  8,  9],
       [20, 22, 24, 26, 28]])

In [ ]:
#untuk melakukan operasi matematik antar array, ukuran array di dimensi yang sama harus sama/salah satu bernilai 1

In [151]:
np.dot(x,y)

1935

In [152]:
x@y #matrix multiplication

1935